---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kspan-sa
  namespace: default
  labels:
    name: kspan-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kspan-sa
  labels:
    name: kspan-sa
rules:
  - apiGroups: [""]
    resources: ["pods","events","deployments","endpoints","services","replicasets","nodes","namespaces","persistentvolumes"]
    verbs: ["list","get","watch"]
  - apiGroups: [ "apps" ]
    resources: [ "deployments","statefulsets","daemonsets","replicasets" ]
    verbs: [ "list","get","watch" ]
  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ "prometheuses" ]
    verbs: [ "list","get","watch" ]
  - apiGroups: [ "dynatrace.com" ]
    resources: [ "dynakubes" ]
    verbs: [ "list","get","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kspan-sa
  labels:
    name: kspan-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kspan-sa
subjects:
  - kind: ServiceAccount
    name: kspan-sa
    namespace: default


